// .ignore/files (2)/Composition.jsx
import { useEffect } from 'react';

// ── gorender contract ──────────────────────────────────────────────────────
// Two hooks: useFrame() gives you the current time,
// useReady() signals gorender when the frame is painted.

function useFrame() {
  const params = new URLSearchParams(window.location.search);
  const frame  = parseInt(params.get('frame') ?? '0', 10);
  const fps    = {{.FPS}};
  return {
    frame,
    fps,
    t: frame / fps,           // seconds
    progress: frame / {{.DurationFrames}}, // 0 → 1
  };
}

function useReady(isReady = true) {
  useEffect(() => {
    if (!isReady) return;
    document.fonts.ready.then(() => {
      window.__READY__ = true;
    });
  }, [isReady]);
}

// ── Utilities ──────────────────────────────────────────────────────────────
const clamp   = (v, min = 0, max = 1) => Math.max(min, Math.min(max, v));
const lerp    = (a, b, t) => a + (b - a) * t;
const easeOut = t => 1 - (1 - t) ** 2;

// ── Composition ────────────────────────────────────────────────────────────
// Drive all styles deterministically from t.
// No useEffect-based animations, no timers, no Date.now().

export default function Composition() {
  const { t, fps } = useFrame();
  const totalSecs = {{.DurationFrames}} / fps;

  const fadeIn   = clamp(t / 0.5);
  const fadeOut  = clamp((totalSecs - t) / 0.5);
  const opacity  = Math.min(fadeIn, fadeOut);
  const slideY   = lerp(40, 0, easeOut(clamp(t / 0.5)));

  // Signal gorender once all hooks have run and DOM is painted.
  useReady(true);

  return (
    <div style={styles.composition}>

      <div style={{
        ...styles.headline,
        opacity,
        transform: `translate(-50%, calc(-50% + ${slideY}px))`,
      }}>
        {{.Name}}
      </div>

      {/* Add your elements here */}

    </div>
  );
}

// ── Styles ─────────────────────────────────────────────────────────────────
// Use px values based on 1080×1920. Never vw/vh.
const styles = {
  composition: {
    width:    1080,
    height:   1920,
    overflow: 'hidden',
    background: '#0a0a0a',
    position: 'relative',
  },
  headline: {
    position:  'absolute',
    top:       '50%',
    left:      '50%',
    color:     'white',
    fontSize:  72,
    fontWeight: 700,
    textAlign: 'center',
  },
};

// .ignore/files (2)/Composition.svelte
<script>
  // ── gorender contract ──────────────────────────────────────────────────
  // Svelte runs at build time — the output is vanilla JS with no runtime.
  // gorender navigates to: ?frame=0, ?frame=1, ?frame=2 ...

  const params = new URLSearchParams(location.search);
  const frame  = parseInt(params.get('frame') ?? '0', 10);
  const fps    = {{.FPS}};
  const t      = frame / fps; // current time in seconds
  const total  = {{.DurationFrames}};
  const totalSecs = total / fps;

  // ── Utilities ────────────────────────────────────────────────────────
  const clamp   = (v, min = 0, max = 1) => Math.max(min, Math.min(max, v));
  const lerp    = (a, b, t) => a + (b - a) * t;
  const easeOut = t => 1 - (1 - t) ** 2;

  // ── Derived animation values ─────────────────────────────────────────
  // Compute everything from t. Svelte's reactivity handles the DOM updates.

  $: fadeIn  = clamp(t / 0.5);
  $: fadeOut = clamp((totalSecs - t) / 0.5);
  $: opacity = Math.min(fadeIn, fadeOut);
  $: translateY = lerp(40, 0, easeOut(clamp(t / 0.5)));

  // ── Signal ready after mount ─────────────────────────────────────────
  import { onMount } from 'svelte';

  onMount(async () => {
    await document.fonts.ready;
    // If you have images, wait for them:
    // await Promise.all(Array.from(document.images).map(waitForImage));
    window.__READY__ = true;
  });
</script>

<!--
  The composition always renders at 1080×1920.
  Never use vw/vh — use px or % of this container.
-->
<div class="composition">

  <div
    class="headline"
    style="opacity: {opacity}; transform: translate(-50%, calc(-50% + {translateY}px))"
  >
    {{.Name}}
  </div>

  <!-- Add your elements here -->

</div>

<style>
  :global(*) { margin: 0; padding: 0; box-sizing: border-box; }

  .composition {
    width: 1080px;
    height: 1920px;
    overflow: hidden;
    background: #0a0a0a;
    position: relative;
  }

  .headline {
    position: absolute;
    top: 50%;
    left: 50%;
    color: white;
    font-size: 72px;
    font-weight: 700;
    text-align: center;
  }
</style>
